### ISSUE TITLE
Organizar links de 2019 en archivos separados

### ISSUE THREAD

**Issue by juan-pineda** [juan-pineda/AvisosParroquiales#2]
@afquinonescamacho , porfa revisar los links que recolectó Maria José, y distribuirlos en los archivos correspondientes. Puedes crear y eliminar categorías a voluntad (creo que la de noticias no es necesaria para el objetivo de este repositorio).

**Comment by afquinonescamacho** [comment]
Me parecería bueno si alguien más mirara si así están bien dispuestos los links y quedaron algunos links sin algo que diga a qué se refieren.
